"""add_is_active_to_roles_and_departments

Revision ID: 74aea769bf54
Revises: d516fc54c3ed
Create Date: 2026-08-11 18:47:10.820430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aea769bf54'
down_revision: Union[str, Sequence[str], None] = 'd516fc54c3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###
