"""update_role_permissions_junction_constraints

Revision ID: 89b0ce83e811
Revises: 00b0eb8a6bf4
Create Date: 2026-08-12 11:41:25.301160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b0ce83e811'
down_revision: Union[str, Sequence[str], None] = '00b0eb8a6bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_permissions_permission_id_permissions'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_role_permissions_role_id_roles'), 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role_permissions', 'created_at')
    # ### end Alembic commands ###
