"""add_code_to_roles_and_departments

Revision ID: a07ed0adb246
Revises: 74aea769bf54
Create Date: 2026-08-11 18:54:41.122501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07ed0adb246'
down_revision: Union[str, Sequence[str], None] = '74aea769bf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('code', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.add_column('roles', sa.Column('code', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_column('roles', 'code')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.drop_column('departments', 'code')
    # ### end Alembic commands ###
