"""create_ai_providers_and_update_ai_models

Revision ID: f7ae5e74af7d
Revises: 89b0ce83e811
Create Date: 2026-08-12 18:03:18.128814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ae5e74af7d'
down_revision: Union[str, Sequence[str], None] = '89b0ce83e811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers'))
    )
    op.create_index(op.f('ix_ai_providers_code'), 'ai_providers', ['code'], unique=True)
    op.create_index(op.f('ix_ai_providers_id'), 'ai_providers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_providers_is_active'), 'ai_providers', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_providers_name'), 'ai_providers', ['name'], unique=False)
    op.add_column('ai_models', sa.Column('provider_id', sa.UUID(), nullable=False))
    op.add_column('ai_models', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('ai_models', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('ai_models', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('ai_models', sa.Column('input_token_price', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('ai_models', sa.Column('output_token_price', sa.Numeric(precision=10, scale=4), nullable=False))
    op.add_column('ai_models', sa.Column('max_output_tokens', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_ai_models_model_name'), table_name='ai_models')
    op.create_index(op.f('ix_ai_models_code'), 'ai_models', ['code'], unique=False)
    op.create_index(op.f('ix_ai_models_is_active'), 'ai_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=False)
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_unique_constraint('uq_ai_models_provider_id_code', 'ai_models', ['provider_id', 'code'])
    op.create_foreign_key(op.f('fk_ai_models_provider_id_ai_providers'), 'ai_models', 'ai_providers', ['provider_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_ai_models_check_input_token_price_non_negative'), 'ai_models', 'input_token_price >= 0')
    op.create_check_constraint(op.f('ck_ai_models_check_max_context_tokens_positive'), 'ai_models', 'max_context_tokens > 0')
    op.create_check_constraint(op.f('ck_ai_models_check_max_output_tokens_positive'), 'ai_models', 'max_output_tokens > 0')
    op.create_check_constraint(op.f('ck_ai_models_check_output_token_price_non_negative'), 'ai_models', 'output_token_price >= 0')
    op.drop_column('ai_models', 'provider')
    op.drop_column('ai_models', 'model_version')
    op.drop_column('ai_models', 'model_name')
    op.drop_column('ai_models', 'output_cost_per_million')
    op.drop_column('ai_models', 'created_by')
    op.drop_column('ai_models', 'model_type')
    op.drop_column('ai_models', 'input_cost_per_million')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('input_cost_per_million', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('ai_models', sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('ai_models', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('ai_models', sa.Column('output_cost_per_million', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('ai_models', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ai_models', sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_models', sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('ck_ai_models_check_output_token_price_non_negative'), 'ai_models', type_='check')
    op.drop_constraint(op.f('ck_ai_models_check_max_output_tokens_positive'), 'ai_models', type_='check')
    op.drop_constraint(op.f('ck_ai_models_check_max_context_tokens_positive'), 'ai_models', type_='check')
    op.drop_constraint(op.f('ck_ai_models_check_input_token_price_non_negative'), 'ai_models', type_='check')
    op.drop_constraint(op.f('fk_ai_models_provider_id_ai_providers'), 'ai_models', type_='foreignkey')
    op.drop_constraint('uq_ai_models_provider_id_code', 'ai_models', type_='unique')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_is_active'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_code'), table_name='ai_models')
    op.create_index(op.f('ix_ai_models_model_name'), 'ai_models', ['model_name'], unique=True)
    op.drop_column('ai_models', 'max_output_tokens')
    op.drop_column('ai_models', 'output_token_price')
    op.drop_column('ai_models', 'input_token_price')
    op.drop_column('ai_models', 'description')
    op.drop_column('ai_models', 'name')
    op.drop_column('ai_models', 'code')
    op.drop_column('ai_models', 'provider_id')
    op.drop_index(op.f('ix_ai_providers_name'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_is_active'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_id'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_code'), table_name='ai_providers')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
