"""add created_by to users

Revision ID: 14529c40ca50
Revises: ff356db00e3b
Create Date: 2026-08-14 10:59:21.349337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14529c40ca50'
down_revision: Union[str, Sequence[str], None] = 'ff356db00e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_foreign_key(op.f('fk_users_created_by_users'), 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_created_by_users'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
