"""create_token_transactions_table

Revision ID: f070b507c09b
Revises: 14529c40ca50
Create Date: 2026-08-18 16:19:24.338739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f070b507c09b'
down_revision: Union[str, Sequence[str], None] = '14529c40ca50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_action', sa.String(length=20), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_sessions.id'], name=op.f('fk_token_transactions_conversation_id_chat_sessions')),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('fk_token_transactions_model_id_ai_models')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_token_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_transactions'))
    )
    op.create_index(op.f('ix_token_transactions_id'), 'token_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_token_transactions_user_id'), 'token_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_transactions_user_id'), table_name='token_transactions')
    op.drop_index(op.f('ix_token_transactions_id'), table_name='token_transactions')
    op.drop_table('token_transactions')
    # ### end Alembic commands ###
